### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by dirk-thomas** [mthak/diskcheck-plugin#2]
Started by upstream project "Jbin_arm_uThf__multisense_cal_check__ubuntu_trusty_armhf__binary" build number 2
    originally caused by:
     Started by user Admin
    Building remotely on building_repository (swarm) in workspace /home/jenkins-slave/workspace/Jrel_sync-packages-to-testing_trusty_armhf
    Disk space threshold is set to :5Gb
    Checking disk space Now 
    FATAL: null
    java.lang.NullPointerException
    	at org.jenkinsci.plugin.Diskcheck.preCheckout(Diskcheck.java:102)
    	at jenkins.scm.SCMCheckoutStrategy.preCheckout(SCMCheckoutStrategy.java:76)
    	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:527)
    	at hudson.model.Run.execute(Run.java:1759)
    	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    	at hudson.model.ResourceController.execute(ResourceController.java:89)
    	at hudson.model.Executor.run(Executor.java:240)

**Comment by dirk-thomas** [comment]
This might be fixed in the upcoming version 0.27 (https://github.com/jenkinsci/diskcheck-plugin/commit/1242bc537b6507bd04faa289c1dfb00a249959d0)?

**Comment by dirk-thomas** [comment]
It has been nine days ago that 0.27 has been committed. When will 0.27 be available via the Jenkins update site?

**Comment by AaronDMarasco-VSI** [comment]
It's been almost a year and I just ran into this bug, and 0.27 still isn't available through the built-in updater. :-1:

**Comment by zvymazal** [comment]
Would be great to get the fix released. We are running into the bug when building on a newly started slave in AWS.

**Comment by thomas-phillips-nz** [comment]
I would like to see this new 0.27 version released too, I have just had to go through and disable the plugin in our jobs after seeing this issue crop up.

Is this project dead now?

**Comment by dirk-thomas** [comment]
I use a Groovy script to perform the check: https://github.com/ros-infrastructure/ros_buildfarm/blob/3686cf4a42835dfc3f0f139934726e2bc42a40f8/ros_buildfarm/templates/snippet/builder_system-groovy_check-free-disk-space.xml.em

And use a daily job to check if any of the disabled nodes can be reenabled: https://github.com/ros-infrastructure/ros_buildfarm/blob/3686cf4a42835dfc3f0f139934726e2bc42a40f8/ros_buildfarm/templates/snippet/builder_system-groovy_check-free-disk-space-disabled-slaves.xml.em

Maybe that is helpful to any of you.
